"""empty message

Revision ID: 8aea3cd9ee1a
Revises: 38db31d198e4
Create Date: 2023-03-18 10:45:36.197871

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "8aea3cd9ee1a"
down_revision = "38db31d198e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("answers_question_id_fkey", "answers", type_="foreignkey")
    op.create_foreign_key(
        None,
        "answers",
        "questions",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("questions_user_id_fkey", "questions", type_="foreignkey")
    op.create_foreign_key(
        None,
        "questions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        "questions_user_id_fkey",
        "questions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        "answers_question_id_fkey",
        "answers",
        "questions",
        ["question_id"],
        ["id"],
    )
    # ### end Alembic commands ###
