"""empty message

Revision ID: 0406fe2d9a02
Revises: f94123368be6
Create Date: 2023-03-19 15:09:25.538251

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0406fe2d9a02"
down_revision = "f94123368be6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_answers", sa.Column("answer_id", sa.Integer(), nullable=True))
    op.alter_column(
        "user_answers",
        "content",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.create_foreign_key(None, "user_answers", "answers", ["answer_id"], ["id"])
    op.drop_column("user_answers", "is_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_answers",
        sa.Column("is_text", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "user_answers", type_="foreignkey")
    op.alter_column(
        "user_answers",
        "content",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.drop_column("user_answers", "answer_id")
    # ### end Alembic commands ###
