version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: poll_us_platform:${POLL_US_PLATFORM_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.8-bullseye
    hostname: poll_us_platform-db
    environment:
      POSTGRES_PASSWORD: ${POLL_US_PLATFORM_DB_PASS}
      POSTGRES_USER: ${POLL_US_PLATFORM_DB_USER}
      POSTGRES_DB: ${POLL_US_PLATFORM_DB_BASE}
    volumes:
    - poll_us_platform-db-data:/var/lib/postgresql/data
    restart: always
    ports:
    - "5432:5432"
    healthcheck:
      test: pg_isready -U poll_us_platform
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: poll_us_platform:${POLL_US_PLATFORM_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  poll_us_platform-db-data:
    name: poll_us_platform-db-data
