version: '3.9'

services:
  api:
    ports:
    - "8000:8000"
    volumes:
    - .:/app/src/
    environment:
      POLL_US_PLATFORM_RELOAD: "True"

  nginx:
    build: ./nginx
    depends_on:
    - api
    ports:
    - "80:80"
    volumes:
    - ./nginx:/etc/nginx/conf.d
    - .:/app/src/
